---

- name: Install
  tags: installation
  when: redis_install
  block:
    - name: Install packages
      ansible.builtin.package: 
        name: 
          - redis6
          - sysfsutils
        state: present
        enablerepo: epel
    
    - name: OS tune role
      ansible.builtin.include_role:
        name: inqwise.common.os_tune
        tasks_from: redis

    - name: Create redis modules folder
      ansible.builtin.file:
        path: "{{ redis_modules_dir }}"
        owner: "{{ redis_user }}" 
        group: "{{ redis_group }}"
        mode: "40755"
        state: directory

- name: Config
  tags: configuration
  when: redis_configure
  block:
    - name: Process modules
      ansible.builtin.include_tasks: module.yml
      loop: "{{ query('fileglob', 'files/modules/' + ansible_architecture + '/*') }}"
      loop_control:
        label: "{{ redis_module }} module" 
      vars:
        redis_module: "{{ item | basename }}"
        src: "modules/{{ ansible_architecture }}"
      
    - name: Debug redis modules
      ansible.builtin.debug:
        var: redis_modules
      run_once: true
      tags: debug

    - name: Create redis data folder
      ansible.builtin.file:
        path: "{{ redis_data_dir }}"
        owner: "{{ redis_user }}" 
        group: "{{ redis_group }}"
        mode: "0755"
        state: directory

    - name: Apply configuration
      ansible.builtin.template:
        src: redis.conf.v6.j2
        dest: "{{ redis_config_path }}"
        owner: "{{ redis_user }}"
        group: root
        mode: "0640"
        backup: true
      register: redisconf
      notify: restart redis
