---

- name: restart zookeeper
  service:
    name: zookeeper 
    state: restarted
    enabled: true
  when: kafka_service_start_and_enable

- name: restart kafka
  service:
    name: kafka 
    state: restarted
    enabled: true
  when: kafka_service_start_and_enable