---
# tasks file for loki
- name: Include OS specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yml"
  tags: always

- name: Deploy Loki service
  ansible.builtin.include_tasks:
    file: "install.yml"
  tags: always
