---
- name: Amazon
  tags: installation
  block:
    - name: Ensure a temporary directory for download exists
      tempfile:
        state: directory
        suffix: download
      register: temp_dir

    - name: check RPM exist in local cache
      stat:
        path: "{{ temp_dir.path }}/openvpn-yum-repository.rpm"
      register: openvpn_repository_install

    - name: download RPM from http
      get_url:
        dest: "{{ temp_dir.path }}/openvpn-yum-repository.rpm"
        url: "{{ openvpn_yum_repository_url }}"
        validate_certs: false
        force: false
      when: openvpn_repository_install.stat.exists == False and openvpn_yum_repository_url.startswith('http')

    - name: download RPM from s3
      command: "aws s3 cp {{ openvpn_yum_repository_url }} {{ temp_dir.path }}/openvpn-yum-repository.rpm"
      when: openvpn_repository_install.stat.exists == False and openvpn_yum_repository_url.startswith('s3')

    - name: install openvpn Repository
      ansible.builtin.package:
        name:
          - "{{ temp_dir.path }}/openvpn-yum-repository.rpm"
        state: present

    - name: Install OpenVPN and dependencies
      ansible.builtin.package:
        name: openvpn-as
        state: present
        lock_timeout: 300