---

- name: Check if hashicorp repo exists
  stat:
    path: /etc/yum.repos.d/hashicorp.repo
  register: hashicorp_repo_result

- name: get hashicorp repo
  get_url:
    url: https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
  when: not hashicorp_repo_result.stat.exists

- name: Install consul
  ansible.builtin.package:
    name: consul
    state: present
