---

- name: Add localhost to resolve
  ansible.builtin.lineinfile:
    path: /etc/dhcp/dhclient.conf
    line: prepend domain-name-servers 127.0.0.1;

- name: Safely use templated variable to run command. Always use the quote filter to avoid injection issues
  ansible.builtin.command: cat /etc/dhcp/dhclient.conf
  register: dhclient_output

- debug: var=dhclient_output

- name: Restart network
  service:
    name: network
    state: restarted
