---
# tasks file for openvpn_as

- name: Include task amazon
  ansible.builtin.include_tasks: amazon.yml
  when: ansible_distribution == "Amazon"
  tags: installation

- name: Set password for openvpn user
  user:
    name: openvpn
    createhome: no
    home: /home/openvpn
    shell: /sbin/nologin
    password: "{{ openvpn_as_password }}"
    update_password: always
    system: yes
    state: present
  tags: installation

- name: Template OpenVPN Access Server main configuration
  template:
    src: as.conf.j2
    dest: /usr/local/openvpn_as/etc/as.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart openvpn_as
  tags: configuration

- name: Configure OpenVPN Access Server
  template:
    src: config.json.j2
    dest: /usr/local/openvpn_as/etc/config.json
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - update db
    - restart openvpn_as
  tags: configuration

- name: create backup folder
  file:
    path: '/opt/backup'
    mode: '41774'
    state: directory
  tags: installation

- include_tasks: restore.yml
  tags: ['configuration','installation']

- name: Ensure OpenVPN Access Server service is started and enabled on boot
  service:
    name: "{{ openvpn_as_service_name }}"
    enabled: yes
    pattern: "{{ openvpn_as_service_name }}"
    state: started
  tags: configuration

- include_tasks: backup.yml
  tags: ['configuration','installation']