---
# handlers file for openvpn_as
- name: update db
  command: ./confdba --load --file=../etc/config.json
  args:
    chdir: /usr/local/openvpn_as/scripts
  ignore_errors: true
  when: openvpn_service_start_and_enable

- name: restart openvpn_as
  service:
    name: "{{ openvpn_as_service_name }}"
    state: restarted
  when: openvpn_service_start_and_enable
