---
# handlers file for openvpn_as

- name: update db
  ansible.builtin.include_tasks: updatedb.yml
  when: openvpn_service_start_and_enable

- name: restart openvpn_as
  service:
    name: "{{ openvpn_as_service_name }}"
    state: restarted
  when: openvpn_service_start_and_enable
