name: Build, Install, and Release Ansible Collection

on:
  push:
    tags:
      - 'v*'  # This triggers the workflow on tag pushes, e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Build the Ansible Collection
      run: |
        ansible-galaxy collection build

    - name: Install the Ansible Collection
      run: |
        ansible-galaxy collection install ./inqwise-stacktrek-1.0.0.tar.gz

    - name: Verify Collection Installation
      run: |
        ansible-galaxy collection list

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./inqwise-stacktrek-1.0.0.tar.gz
        asset_name: inqwise-stacktrek-1.0.0.tar.gz
        asset_content_type: application/gzip
